# Generated by Django 5.2 on 2025-04-27 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, unique=True)),
                ('game_type', models.CharField(choices=[('roulette', 'Roulette'), ('slots', 'Slots'), ('blackjack', 'Blackjack'), ('poker', 'Poker'), ('sports', 'Sports')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'games',
                'indexes': [models.Index(fields=['game_name'], name='games_game_na_304dce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bet_status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='website.game')),
            ],
            options={
                'db_table': 'bets',
                'indexes': [models.Index(fields=['gambler', 'placed_at'], name='bets_gambler_1f903d_idx'), models.Index(fields=['bet_status'], name='bets_bet_sta_cc8394_idx')],
            },
        ),
    ]
