# Generated by Django 5.2 on 2025-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_game_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('avg_total_bets', models.FloatField()),
                ('avg_total_stake', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_avg_stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_max_stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_min_stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_total_payout', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_win_count', models.FloatField()),
                ('avg_total_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_win_rate', models.FloatField()),
            ],
            options={
                'db_table': 'stats',
            },
        ),
    ]
