# Generated by Django 5.2 on 2025-05-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamblerScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_scan', models.BooleanField(default=False)),
                ('previous_scan', models.DateTimeField(blank=True, null=True)),
                ('loss_chasing_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loss_chasing_severity', models.CharField(max_length=20)),
                ('fluctuating_wagers_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fluctuating_wagers_severity', models.CharField(max_length=20)),
                ('impulsive_transactions_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impulsive_transactions_severity', models.CharField(max_length=20)),
                ('binge_gambling_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('binge_gambling_severity', models.CharField(max_length=20)),
                ('monetary_consumption_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monetary_consumption_severity', models.CharField(max_length=20)),
                ('cluster_label', models.CharField(max_length=50)),
                ('gambler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gambler_scan_results',
            },
        ),
    ]
