# Generated by Django 5.2 on 2025-05-30 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_gamblerscanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('loss_chasing', 'Loss Chasing'), ('binge_gambling', 'Binge Gambling'), ('impulsive_transactions', 'Impulsive Transactions'), ('fluctuating_wagers', 'Fluctuating Wagers'), ('monetary_consumption', 'Monetary Consumption'), ('highest_bet', 'Highest Bet')], max_length=32)),
                ('explanation', models.TextField()),
                ('actions_taken', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
                'unique_together': {('gambler', 'trigger_type')},
            },
        ),
    ]
