# Generated by Django 5.2 on 2025-05-30 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('report_message', models.TextField()),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'self_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
