# Generated by Django 5.2 on 2025-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_selfreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamblerscanresult',
            name='avg_stake',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='max_stake',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='min_stake',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='total_bets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='total_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='total_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='total_stake',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='gamblerscanresult',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
