# Generated by Django 5.2 on 2025-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_gamblerscanresult_avg_stake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfreport',
            name='action',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
